version: '3'

services:

  mysql_container_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hanah
      - MYSQL_DATABASE=school_library 
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/docker/volumes/project-devops-volume/_data:/var/lib/mysql

  backend-app:
    image: hanaghz/demo-app:devops-1.0
    restart: on-failure
    depends_on:
      - mysql_container_db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql_container_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=hanah
      - DATABASE_NAME=school_library
      - DATABASE_PORT=3307

